### PR TITLE
Merge request from loginFeaturebranch to master

### PR DESCRIPTION
**Pull request by chiragkhimani**
Can you pleasse merge it? I've tested everything and it's working fine.

### CODE REVIEW

**Comment by tim181** [comment]
good

**Comment by mkaraduman0** [comment]
image
Line 6 has an issue. You are fired

**Comment by rabiadoga** [comment]
perfect

**Comment by Innaananyeva** [comment]
Great job!

**Comment by chiragkhimani** [comment]
@mkaraduman0 - I'll fix it asap

**Review by mkaraduman0 — APPROVED** [review]

**Review by Alicetin06 — APPROVED** [review]

**Review by ynates — APPROVED** [review]
looks good

**Review by Rukhshona123 — APPROVED** [review]

**Review by rabiadoga — APPROVED** [review]

**Review by mehrona776 — COMMENTED** [review]
Incredible!!!

**Comment by tim181** [comment]
he

**Review by Innaananyeva — COMMENTED** [review]
Please, review line 6. It's incorrect

**Pull request merged**
